name: Pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: GitHub Pages (en)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          make deps

      - name: Build Packages
        run: |
          make LANG=en

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./output/en
            cname: pinout.xyz
